apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
