apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
