version: '3'
 
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    volumes:
    - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    ports:
      - 5432:5432
 
  frontend:
    image: udagram-frontend
    container_name: udagram-frontend
    build:
      dockerfile: udagram-frontend/Dockerfile
      context: .
    ports:
      - 4200:4200
      - 8111:80
    restart: unless-stopped
 
  api:
    image: udagram-api
    container_name: udagram-api
    build:
      dockerfile: udagram-api/Dockerfile
      context: .
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
    - POSTGRES_USERNAME=$POSTGRES_USERNAME
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_HOST=$POSTGRES_HOST
    - POSTGRES_DB=$POSTGRES_DB
    - AWS_BUCKET=$AWS_BUCKET
    - AWS_REGION=$AWS_REGION
    - AWS_PROFILE=$AWS_PROFILE
    - JWT_SECRET=$JWT_SECRET
    - URL=$URL
  
  user-api:
    image: udagram-api-user
    container_name: udagram-api-user
    build:
      dockerfile: udagram-api-user/Dockerfile
      context: .
    ports:
      - 8010:8080
    restart: unless-stopped
    environment:
    - POSTGRES_USERNAME=$POSTGRES_USERNAME
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_HOST=$POSTGRES_HOST
    - POSTGRES_DB=$POSTGRES_DB
    - AWS_BUCKET=$AWS_BUCKET
    - AWS_REGION=$AWS_REGION
    - AWS_PROFILE=$AWS_PROFILE
    - JWT_SECRET=$JWT_SECRET
    - URL=$URL

  feed-api:
    image: udagram-api-feed
    container_name: udagram-api-feed
    build:
      dockerfile: udagram-api-feed/Dockerfile
      context: .
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - 8020:8080
    restart: unless-stopped
    environment:
    - POSTGRES_USERNAME=$POSTGRES_USERNAME
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_HOST=$POSTGRES_HOST
    - POSTGRES_DB=$POSTGRES_DB
    - AWS_BUCKET=$AWS_BUCKET
    - AWS_REGION=$AWS_REGION
    - AWS_PROFILE=$AWS_PROFILE
    - JWT_SECRET=$JWT_SECRET
    - URL=$URL
       
  reverseproxy:
    image: reverseproxy
    container_name: reverseproxy
    build:
      dockerfile: udagram-reverseproxy/Dockerfile
      context: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - user-api
      - feed-api
networks:
  default:
    driver: bridge
 
volumes:
  postgres-db-volume:
