apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: ayomide265/udagram-api-user:v3
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: udagramdb-env
          - secretRef:
              name: udagramdb-env
