apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  ports:
  - port: 8080
    name: "8080"
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-user

