apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  namespace: default
  labels:
    app: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    app: udagram-frontend