apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: reverseproxy