apiVersion: v1
kind: Service
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  ports:
  - port: 8080 # expose port
    targetPort: 8080 # container port
    protocol: TCP
  selector:
    app: feed-api
