apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80 # expose port
    targetPort: 80 # container port
    protocol: TCP
  selector:
    run: frontend
