apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend

