apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  namespace: default
  labels:
    app: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: udagram-frontend