apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy-service
  namespace: default
  labels:
    app: udagram-reverse-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-reverse-proxy