apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-feed
  type: ClusterIP
status:
  loadBalancer: {}